<?php
return [
    //POST
    'checkupdateaccesstoken'                    => ['controller' => 'TokenController',          'method' => 'checkUpdateAccessToken'],
    'checkupdaterefreshtoken'                   => ['controller' => 'TokenController',          'method' => 'checkUpdateRefreshToken'],
    'getupdatetime'                             => ['controller' => 'TokenController',          'method' => 'getUpdateTime'],
    'getsitekey'                                => ['controller' => 'TokenController',          'method' => 'getSiteKey'],
    'contact'                                   => ['controller' => 'ContactController',        'method' => 'sendContact'],
    'getusereditableinfo'                       => ['controller' => 'UserController',           'method' => 'getUserEditableInfo'],
    'createuser'                                => ['controller' => 'UserController',           'method' => 'createUser'],
    'googlecreateuser'                          => ['controller' => 'UserController',           'method' => 'googleCreateUser'],
    'updateuser'                                => ['controller' => 'UserController',           'method' => 'updateUser'],
    'updatepassword'                            => ['controller' => 'UserController',           'method' => 'updatePassword'],
    'removeuser'                                => ['controller' => 'UserController',           'method' => 'deleteUser'],
    'loginuser'                                 => ['controller' => 'UserController',           'method' => 'loginUser'],
    'googleloginuser'                           => ['controller' => 'UserController',           'method' => 'googleLoginUser'],
    'logoutuser'                                => ['controller' => 'UserController',           'method' => 'logoutUser'],
    'passwordreset'                             => ['controller' => 'UserController',           'method' => 'passwordReset'],
    'forgotpassword'                            => ['controller' => 'UserController',           'method' => 'forgotPassword'],
    'storeflightdetails'                        => ['controller' => 'BookController',           'method' => 'storeFlightDetails'],
    'storepassengerdetails'                     => ['controller' => 'BookController',           'method' => 'storePassengerDetails'],
    'storebookservicesdetails'                  => ['controller' => 'BookController',           'method' => 'storeBookServicesDetails'],
    'storeprimarycontactinformationdetails'     => ['controller' => 'BookController',           'method' => 'storePrimaryContactInformationDetails'],
    'paymentdetails'                            => ['controller' => 'BookController',           'method' => 'paymentDetails'],
    'checkin'                                   => ['controller' => 'BookController',           'method' => 'checkin'],
    'getsummarybooks'                           => ['controller' => 'BookController',           'method' => 'getSummaryBooks'],
    'getbookinfo'                               => ['controller' => 'BookController',           'method' => 'getBookInfo'],
    'cancelbook'                                => ['controller' => 'BookController',           'method' => 'cancelBook'],
    'getassistivedevices'                       => ['controller' => 'OptionsController',        'method' => 'getAssistiveDevices'],
    'getmedicalequipments'                      => ['controller' => 'OptionsController',        'method' => 'getMedicalEquipments'],
    'getmobilitylimitations'                    => ['controller' => 'OptionsController',        'method' => 'getMobilityLimitations'],
    'getcommunicationneeds'                     => ['controller' => 'OptionsController',        'method' => 'getCommunicationNeeds'],
    'getmedicationrequirements'                 => ['controller' => 'OptionsController',        'method' => 'getMedicationRequirements'],
    'getdoctypes'                               => ['controller' => 'OptionsController',        'method' => 'getDocTypes'],
    'getdoctypeses'                             => ['controller' => 'OptionsController',        'method' => 'getDocTypesEs'],
    'getagecategories'                          => ['controller' => 'OptionsController',        'method' => 'getAgeCategories'],
    'getoptions'                                => ['controller' => 'OptionsController',        'method' => 'getOptions'],
    'getcompanyinfo'                            => ['controller' => 'PageDetailsController',    'method' => 'getCompanyInfo'],
    //GET
    'gotopasswordreset'                         => ['controller' => 'EmailLinkActionController', 'method' => 'goToPasswordReset'],
    'gotoemailverification'                     => ['controller' => 'EmailLinkActionController', 'method' => 'goToEmailVerification'],
    'gotoaccountdeletion'                       => ['controller' => 'EmailLinkActionController', 'method' => 'goToAccountDeletion'],
    'paypalredirectok'                          => ['controller' => 'PaymentController',        'method' => 'paypalRedirectOk'],
    'paypalredirectcancel'                      => ['controller' => 'PaymentController',        'method' => 'paypalRedirectCancel'],
    //SOLO PARA DEBUG
    'obtenervariablesdesesiondebug'             => ['controller' => 'DebugController',          'method' => 'obtenerVariablesDeSesionDebug'],
    'debugpaypalredirectok'                     => ['controller' => 'DebugController',          'method' => 'debugPaypalRedirectOk']
];
